title: MAS0000
code: MAS0000
year: 2018-19
author: Ann Example
top_links:
  - title: Mock Test
    icon: fa-graduation-cap
    url: https://numbas.mathcentre.ac.uk/test-yourself/maths-support-diagnostic-test-differentiation/
  - title: Information
    icon: fa-info-circle
    url: /module/MAS0000/
structure: 
    - type: introduction
      source: intro.tex
    - type: part
      title: Course Material
      content:
        - type: chapter
          title: Chapter 1
          source: chapter1/chapter1.tex
        - type: chapter
          title: Chapter 2
          source: chapter2/chapter2.tex
    - type: part
      title: Demonstration
      content:
        - type: chapter
          title: First-order ODEs
          source: numbasdemo/chapter1.tex
        - type: chapter
          title: ANOVA Code Demo
          source: code/code-psy2010.md
        - type: url
          title: URL Test
          source: https://mas-coursebuild.ncl.ac.uk/p/GwI2wDgTgdhBaAZsAjAE3gFgKYGYCs8IAxgfAEzBpoqIrD6RpA==/
          hidden: true
themes: 
  - title: Default
    source: NCLCourse
    path: default 
  - title: Accessible
    source: accessible
    path: accessible
build_pdf: True
