title: "Sample Course"
code: SAM0000
year: 2020
base_dir: sample_course
author: Ann Example
structure: 
    - type: introduction
      source: intro.tex
      leading_text: "This is a short paragraph that will be 
      inserted into the introduction page, just under the author and year."
    - type: part
      title: Notes
      content:
        - type: chapter
          title: LaTeX notes
          source: latex/latex.tex
        - type: chapter
          title: RevTeX article
          source: revtex/revtex.tex
        - type: chapter
          title: Markdown notes
          source: markdown/handout.md
    - type: part
      title: Slides
      content:
        - type: slides
          title: Markdown Slides
          source: markdown/lecture.md
        - type: slides
          title: Beamer Slides
          source: slides/slides.tex
    - type: part
      title: Other Content
      content:
        - type: chapter
          title: Figures and Embedding
          source: latex/figures_embed.tex
        - type: notebook
          title: Jupyter Notebook notes
          source: markdown/handout.md
        - type: url
          title: An External URL
          source: "https://bbc.co.uk/"
        - type: url
          title: A Static File
          source: static/data/dataset.RData
build_pdf: true
