title: "Sample Course"
code: SAM0000
year: 2020
base_dir: sample_course
author: Ann Example
structure: 
    - type: introduction
      source: intro.tex
      leading_text: "This is a short paragraph that will be 
      inserted into the introduction page, just under the author and year."
    - type: part
      title: Course Material
      content:
        - type: chapter
          title: LaTeX notes
          source: latex.tex
        - type: chapter
          title: Markdown notes
          source: markdown.md
        - type: chapter
          title: Figures and Embedding
          source: figures_embed.tex
        - type: url
          title: An External URL
          source: "https://bbc.co.uk/"
    - type: part
      title: Slides
      content:
        - type: slides
          title: Markdown Slides
          source: slides/slides.md
        - type: slides
          title: Beamer Slides
          source: slides/slides.tex
themes: 
  - title: Default
    source: default
    path: default
build_pdf: True
