title: "MAS0000: Example Content"
code: MAS0000
year: 2018-19
base_dir: lti/content
author: Ann Example
structure: 
    - type: introduction
      source: intro.tex
      leading_text: "This is a short paragraph that will be 
      inserted into the introduction page, just under the author and year."
    - type: part
      title: Course Material
      content:
        - type: chapter
          title: Chapter 1
          source: chapter1/chapter1.tex
        - type: chapter
          title: Embed Demo
          source: chapter2/chapter2.tex
        - type: url
          title: URL Test
          source: "https://bbc.co.uk/"
    - type: part
      title: Slides
      content:
        - type: slides
          title: Markdown Slides
          source: slides/slides.md
    - type: part
      title: Assessment 
      content:
        - type: exam 
          title: Example exam
          source: exam/example_exam.tex
themes: 
  - title: Default
    source: default
    path: default
  - title: Accessible
    source: accessible
    path: accessible
build_pdf: True
