title: MAS0000
code: MAS0000
year: 2018-19
base_dir: module
author: Ann Example
structure: 
    - type: introduction
      source: intro.tex
    - type: part
      title: Course Material
      content:
        - type: chapter
          title: Chapter 1
          source: chapter1/chapter1.tex
        - type: chapter
          title: Chapter 2
          source: chapter2/chapter2.tex
    - type: part
      title: Demonstration
      content:
        - type: chapter
          title: First-order ODEs
          source: numbasdemo/chapter1.tex
        - type: chapter
          title: Code Demo
          source: code/code.md
#        - type: url
#          title: URL Test
#          source: https://mas-coursebuild.ncl.ac.uk/p/GwI2wDgTgdhBaAZsAjAE3gFgKYGYCs8IAxgfAEzBpoqIrD6RpA==/
#          hidden: True
    - type: part
      title: Assessment 
      content:
        - type: chapter
          title: Example exam
          source: exam/example_exam.tex
themes: 
  - title: Default
    source: customisable
    path: customisable
  - title: Large text
    source: accessible
    path: accessible
build_pdf: True
