name: Build

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-build:
    runs-on: ubuntu-latest
    container: coursebuilder/coursebuilder-docker:latest
    steps:
    - uses: actions/checkout@v2
    - name: Run the makecourse script
      run: make
    - name: Copy redirection index
      run: cp .github/workflows/index.html build/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
