name: Build

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-build:
    runs-on: ubuntu-latest
    container: coursebuilder/chirun-docker:latest
    steps:
    - uses: actions/checkout@v2
    - name: Run the chirun script
      run: make
    - name: Setup webdirectory
      run: mkdir -p deploy/ && cp -r build/* deploy/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
